### PR TITLE
26 fe get one exam page feature 1

### PR DESCRIPTION
**Pull request by isabessa05**
# Changelog
All notable changes to this project will be documented in this file.

# Issue(s)
#26 

## General Description:
We are now able to see one single exam on the /examdetail route. This was performed by adding a useContext, since the mock API doesn't have the access to a single exam request. 

### Added:

- useContext hook
- Context folder for examContext
- ExamInfo component
- PatientInfo component (this can be removed since is not in use yet)
- ExamDetail page

### Changed:
ChakraLink was used on the <Td> with examId, which now makes it clickable and redirects you to /examdetail page.

### Removed
None

### Planned
Addition of CSS for this specific display, and work on issue for PatientInfo

### Required Reviewers
- PRs require two reviewers to merge to main
@ylopez25 @ccelest1

### CODE REVIEW

**Review by ylopez25 — APPROVED** [review]
Looks good! I am curious about user_stories.md because it changed but if it looks correct to me so I'll go ahead and approve.

**Comment by isabessa05** [comment]
> Looks good! I am curious about user_stories.md because it changed but if it looks correct to me so I'll go ahead and approve.

Same, user_stories keeps giving me an error so I just reset the changes to be able to commit and push.

**Comment by ccelest1** [comment]
@isabessa05 @ylopez25 I'm having the same glitch with that file and the reason is because Ben titled a file the same exact name in a prior update and as a result there will be continued conflicts as it continues to rewrite itself. I just removed it for this branch and have it moved into another folder on my separate branch so when I merge eventually it will be included without this weird commit glitch

 I see there are merge conflicts to be resolved. lmk if you can do them @isabessa05 via the instructions:
Screenshot 2024-02-12 at 1 14 01 PM

Then I'll approve. Apologies for being late

**Comment by ccelest1** [comment]
This is good work. Made a few additions and resolved the overscrolling, unique key prop issues.

**Review by ccelest1 — COMMENTED** [review]
Merged

**Pull request merged**
