### PR TITLE
Actual Admin Page

### PR DESCRIPTION
**Pull request by ccelest1**
# Changelog
All notable changes to this project will be documented in this file.

# Issue(s)
#69 

## General Description:
 Submitting a new pr containing actual new edits, finalized admin

### Added:
Actual Admin Page with setup

### Planned
Fix console errors and fix notifications on creation of exam pages (matter of getting state `submission, setSubmission` more accurately as opposed to the delayed implementation it currently has) using Toast

### Required Reviewers
@Benjamin-Ortiz

### CODE REVIEW

**Comment by Benjamin-Ortiz** [comment]
I'd also switch the exam id and patient id columns. The mongo _ids are visually chaotic, if its put in the middle it'll visually even out. Once that and the merge conflicts are dealt with, we can integrate it. It looks awesome !

**Comment by ccelest1** [comment]
> I'd also switch the exam id and patient id columns. The mongo _ids are visually chaotic, if its put in the middle it'll visually even out. Once that and the merge conflicts are dealt with, we can integrate it. It looks awesome !

Sounds good, planning on handling conflicts tomorrow in order to finish.

**Comment by ccelest1** [comment]
Putting the mongo id in the middle @Benjamin-Ortiz doesn't even it out, it makes the table lopsided, so I ended up taking it out

**Comment by ccelest1** [comment]
@Benjamin-Ortiz cleaned up, please review

**Comment by Benjamin-Ortiz** [comment]
read my mind with that clean up, good job

**Pull request merged**
